"""
Módulo de dados de cursos para o sistema de recomendação.
Contém cursos de diversos níveis: Técnico, Graduação, Pós-graduação,
Mestrado, Doutorado e Pós-doutorado.
"""

COURSES = [
    # ============ CURSOS TÉCNICOS ============
    {
        "id": 1,
        "nome": "Técnico em Informática",
        "nivel": "Técnico",
        "area": "Tecnologia",
        "assuntos": ["programação", "redes", "banco de dados", "hardware"],
        "duracao_meses": 18,
        "horario": "Noturno",
        "modalidade": "Presencial",
        "preco_mensal": 350.00,
        "instituicao": "SENAI",
        "cidade": "São Paulo",
        "nota_mec": 4,
        "descricao": "Formação técnica completa em informática com foco em programação e manutenção de sistemas."
    },
    {
        "id": 2,
        "nome": "Técnico em Enfermagem",
        "nivel": "Técnico",
        "area": "Saúde",
        "assuntos": ["anatomia", "farmacologia", "cuidados ao paciente", "biossegurança"],
        "duracao_meses": 24,
        "horario": "Matutino",
        "modalidade": "Presencial",
        "preco_mensal": 450.00,
        "instituicao": "SENAC",
        "cidade": "Rio de Janeiro",
        "nota_mec": 5,
        "descricao": "Curso técnico em enfermagem com estágio supervisionado em hospitais e clínicas."
    },
    {
        "id": 3,
        "nome": "Técnico em Mecatrônica",
        "nivel": "Técnico",
        "area": "Engenharia",
        "assuntos": ["automação", "robótica", "eletrônica", "mecânica"],
        "duracao_meses": 24,
        "horario": "Vespertino",
        "modalidade": "Presencial",
        "preco_mensal": 500.00,
        "instituicao": "SENAI",
        "cidade": "Curitiba",
        "nota_mec": 5,
        "descricao": "Formação em mecatrônica com laboratórios modernos e projetos práticos de automação industrial."
    },
    {
        "id": 4,
        "nome": "Técnico em Administração",
        "nivel": "Técnico",
        "area": "Negócios",
        "assuntos": ["gestão", "finanças", "marketing", "recursos humanos"],
        "duracao_meses": 12,
        "horario": "Noturno",
        "modalidade": "EAD",
        "preco_mensal": 250.00,
        "instituicao": "ETEC",
        "cidade": "São Paulo",
        "nota_mec": 4,
        "descricao": "Curso técnico em administração com foco em gestão de pequenas e médias empresas."
    },
    {
        "id": 5,
        "nome": "Técnico em Design Gráfico",
        "nivel": "Técnico",
        "area": "Artes e Design",
        "assuntos": ["design", "ilustração", "edição de imagem", "tipografia"],
        "duracao_meses": 15,
        "horario": "Matutino",
        "modalidade": "Presencial",
        "preco_mensal": 400.00,
        "instituicao": "SENAC",
        "cidade": "Belo Horizonte",
        "nota_mec": 4,
        "descricao": "Formação em design gráfico com ferramentas profissionais Adobe e projetos reais de mercado."
    },

    # ============ GRADUAÇÃO ============
    {
        "id": 6,
        "nome": "Ciência da Computação",
        "nivel": "Graduação",
        "area": "Tecnologia",
        "assuntos": ["algoritmos", "inteligência artificial", "engenharia de software", "programação"],
        "duracao_meses": 48,
        "horario": "Integral",
        "modalidade": "Presencial",
        "preco_mensal": 1800.00,
        "instituicao": "USP",
        "cidade": "São Paulo",
        "nota_mec": 5,
        "descricao": "Bacharelado em Ciência da Computação com forte base matemática e projetos de pesquisa."
    },
    {
        "id": 7,
        "nome": "Engenharia Civil",
        "nivel": "Graduação",
        "area": "Engenharia",
        "assuntos": ["estruturas", "construção", "geotecnia", "hidráulica"],
        "duracao_meses": 60,
        "horario": "Integral",
        "modalidade": "Presencial",
        "preco_mensal": 2200.00,
        "instituicao": "UNICAMP",
        "cidade": "Campinas",
        "nota_mec": 5,
        "descricao": "Engenharia Civil com laboratórios de ponta e parcerias com empresas do setor."
    },
    {
        "id": 8,
        "nome": "Medicina",
        "nivel": "Graduação",
        "area": "Saúde",
        "assuntos": ["anatomia", "fisiologia", "patologia", "clínica médica"],
        "duracao_meses": 72,
        "horario": "Integral",
        "modalidade": "Presencial",
        "preco_mensal": 8500.00,
        "instituicao": "UNIFESP",
        "cidade": "São Paulo",
        "nota_mec": 5,
        "descricao": "Curso de Medicina com residência integrada e hospital universitário próprio."
    },
    {
        "id": 9,
        "nome": "Administração de Empresas",
        "nivel": "Graduação",
        "area": "Negócios",
        "assuntos": ["gestão", "finanças", "empreendedorismo", "marketing"],
        "duracao_meses": 48,
        "horario": "Noturno",
        "modalidade": "Presencial",
        "preco_mensal": 1200.00,
        "instituicao": "FGV",
        "cidade": "São Paulo",
        "nota_mec": 5,
        "descricao": "Graduação em Administração com cases reais e intercâmbio internacional."
    },
    {
        "id": 10,
        "nome": "Direito",
        "nivel": "Graduação",
        "area": "Humanas",
        "assuntos": ["direito civil", "direito penal", "constitucional", "trabalhista"],
        "duracao_meses": 60,
        "horario": "Matutino",
        "modalidade": "Presencial",
        "preco_mensal": 1500.00,
        "instituicao": "PUC",
        "cidade": "Rio de Janeiro",
        "nota_mec": 5,
        "descricao": "Bacharelado em Direito com núcleo de prática jurídica e convênios com tribunais."
    },
    {
        "id": 11,
        "nome": "Psicologia",
        "nivel": "Graduação",
        "area": "Saúde",
        "assuntos": ["psicologia clínica", "neurociência", "psicologia social", "desenvolvimento humano"],
        "duracao_meses": 60,
        "horario": "Matutino",
        "modalidade": "Presencial",
        "preco_mensal": 1400.00,
        "instituicao": "UFMG",
        "cidade": "Belo Horizonte",
        "nota_mec": 5,
        "descricao": "Formação em Psicologia com clínica-escola e estágios em diversas áreas."
    },
    {
        "id": 12,
        "nome": "Análise e Desenvolvimento de Sistemas",
        "nivel": "Graduação",
        "area": "Tecnologia",
        "assuntos": ["programação", "banco de dados", "desenvolvimento web", "mobile"],
        "duracao_meses": 30,
        "horario": "Noturno",
        "modalidade": "EAD",
        "preco_mensal": 350.00,
        "instituicao": "UNIP",
        "cidade": "São Paulo",
        "nota_mec": 4,
        "descricao": "Tecnólogo em ADS com foco prático em desenvolvimento de sistemas e metodologias ágeis."
    },

    # ============ PÓS-GRADUAÇÃO (ESPECIALIZAÇÃO) ============
    {
        "id": 13,
        "nome": "MBA em Gestão de Projetos",
        "nivel": "Pós-graduação",
        "area": "Negócios",
        "assuntos": ["gestão de projetos", "metodologias ágeis", "liderança", "planejamento estratégico"],
        "duracao_meses": 18,
        "horario": "Noturno",
        "modalidade": "Presencial",
        "preco_mensal": 900.00,
        "instituicao": "FGV",
        "cidade": "São Paulo",
        "nota_mec": 5,
        "descricao": "MBA com certificação PMI e professores com experiência executiva."
    },
    {
        "id": 14,
        "nome": "Especialização em Inteligência Artificial",
        "nivel": "Pós-graduação",
        "area": "Tecnologia",
        "assuntos": ["machine learning", "deep learning", "processamento de linguagem natural", "visão computacional"],
        "duracao_meses": 12,
        "horario": "Sábados",
        "modalidade": "Híbrido",
        "preco_mensal": 1100.00,
        "instituicao": "FIAP",
        "cidade": "São Paulo",
        "nota_mec": 4,
        "descricao": "Especialização em IA com projetos práticos usando TensorFlow, PyTorch e dados reais."
    },
    {
        "id": 15,
        "nome": "Pós-graduação em Direito Digital",
        "nivel": "Pós-graduação",
        "area": "Humanas",
        "assuntos": ["LGPD", "cibersegurança jurídica", "propriedade intelectual", "contratos digitais"],
        "duracao_meses": 15,
        "horario": "Noturno",
        "modalidade": "EAD",
        "preco_mensal": 750.00,
        "instituicao": "IDP",
        "cidade": "Brasília",
        "nota_mec": 4,
        "descricao": "Pós em Direito Digital com foco em LGPD, regulação de tecnologia e crimes cibernéticos."
    },
    {
        "id": 16,
        "nome": "Especialização em Medicina do Esporte",
        "nivel": "Pós-graduação",
        "area": "Saúde",
        "assuntos": ["fisiologia do exercício", "nutrição esportiva", "reabilitação", "biomecânica"],
        "duracao_meses": 18,
        "horario": "Sábados",
        "modalidade": "Presencial",
        "preco_mensal": 1300.00,
        "instituicao": "UNIFESP",
        "cidade": "São Paulo",
        "nota_mec": 5,
        "descricao": "Especialização médica com atuação em clubes esportivos e atletas de alto rendimento."
    },
    {
        "id": 17,
        "nome": "MBA em Data Science",
        "nivel": "Pós-graduação",
        "area": "Tecnologia",
        "assuntos": ["estatística", "machine learning", "big data", "visualização de dados"],
        "duracao_meses": 12,
        "horario": "Noturno",
        "modalidade": "EAD",
        "preco_mensal": 800.00,
        "instituicao": "USP/Esalq",
        "cidade": "Piracicaba",
        "nota_mec": 5,
        "descricao": "MBA em Data Science com projetos reais de empresas parceiras e mentoria individual."
    },

    # ============ MESTRADO ============
    {
        "id": 18,
        "nome": "Mestrado em Ciência da Computação",
        "nivel": "Mestrado",
        "area": "Tecnologia",
        "assuntos": ["inteligência artificial", "computação distribuída", "segurança da informação", "teoria da computação"],
        "duracao_meses": 24,
        "horario": "Integral",
        "modalidade": "Presencial",
        "preco_mensal": 0.00,
        "instituicao": "USP",
        "cidade": "São Paulo",
        "nota_mec": 7,
        "descricao": "Mestrado acadêmico com bolsa CAPES/CNPq disponível e laboratórios de pesquisa de ponta."
    },
    {
        "id": 19,
        "nome": "Mestrado em Engenharia Biomédica",
        "nivel": "Mestrado",
        "area": "Engenharia",
        "assuntos": ["bioengenharia", "instrumentação médica", "processamento de sinais", "biomateriais"],
        "duracao_meses": 24,
        "horario": "Integral",
        "modalidade": "Presencial",
        "preco_mensal": 0.00,
        "instituicao": "UNICAMP",
        "cidade": "Campinas",
        "nota_mec": 7,
        "descricao": "Mestrado interdisciplinar entre engenharia e medicina com parcerias internacionais."
    },
    {
        "id": 20,
        "nome": "Mestrado Profissional em Administração",
        "nivel": "Mestrado",
        "area": "Negócios",
        "assuntos": ["estratégia empresarial", "inovação", "finanças corporativas", "gestão de pessoas"],
        "duracao_meses": 24,
        "horario": "Noturno",
        "modalidade": "Presencial",
        "preco_mensal": 3500.00,
        "instituicao": "FGV",
        "cidade": "São Paulo",
        "nota_mec": 6,
        "descricao": "Mestrado profissional voltado para executivos com dissertação aplicada a problemas reais."
    },
    {
        "id": 21,
        "nome": "Mestrado em Neurociências",
        "nivel": "Mestrado",
        "area": "Saúde",
        "assuntos": ["neurobiologia", "cognição", "neuropsicologia", "neuroimagem"],
        "duracao_meses": 24,
        "horario": "Integral",
        "modalidade": "Presencial",
        "preco_mensal": 0.00,
        "instituicao": "UFRJ",
        "cidade": "Rio de Janeiro",
        "nota_mec": 7,
        "descricao": "Mestrado em Neurociências com acesso a equipamentos de ressonância magnética funcional."
    },
    {
        "id": 22,
        "nome": "Mestrado em Educação",
        "nivel": "Mestrado",
        "area": "Humanas",
        "assuntos": ["pedagogia", "didática", "políticas educacionais", "tecnologia educacional"],
        "duracao_meses": 24,
        "horario": "Vespertino",
        "modalidade": "Presencial",
        "preco_mensal": 0.00,
        "instituicao": "UFMG",
        "cidade": "Belo Horizonte",
        "nota_mec": 6,
        "descricao": "Mestrado acadêmico em Educação com linhas de pesquisa em tecnologia e inclusão."
    },

    # ============ DOUTORADO ============
    {
        "id": 23,
        "nome": "Doutorado em Inteligência Artificial",
        "nivel": "Doutorado",
        "area": "Tecnologia",
        "assuntos": ["aprendizado profundo", "robótica cognitiva", "IA explicável", "computação quântica"],
        "duracao_meses": 48,
        "horario": "Integral",
        "modalidade": "Presencial",
        "preco_mensal": 0.00,
        "instituicao": "USP",
        "cidade": "São Carlos",
        "nota_mec": 7,
        "descricao": "Doutorado em IA com colaboração com MIT e Stanford, publicações em conferências top."
    },
    {
        "id": 24,
        "nome": "Doutorado em Genética Molecular",
        "nivel": "Doutorado",
        "area": "Saúde",
        "assuntos": ["genômica", "CRISPR", "bioinformática", "terapia gênica"],
        "duracao_meses": 48,
        "horario": "Integral",
        "modalidade": "Presencial",
        "preco_mensal": 0.00,
        "instituicao": "UNICAMP",
        "cidade": "Campinas",
        "nota_mec": 7,
        "descricao": "Doutorado com laboratório de sequenciamento genômico de última geração e bolsa integral."
    },
    {
        "id": 25,
        "nome": "Doutorado em Economia",
        "nivel": "Doutorado",
        "area": "Negócios",
        "assuntos": ["macroeconomia", "econometria", "economia comportamental", "políticas públicas"],
        "duracao_meses": 48,
        "horario": "Integral",
        "modalidade": "Presencial",
        "preco_mensal": 0.00,
        "instituicao": "FGV/EPGE",
        "cidade": "Rio de Janeiro",
        "nota_mec": 7,
        "descricao": "Doutorado em Economia com corpo docente internacional e publicações em journals de impacto."
    },
    {
        "id": 26,
        "nome": "Doutorado em Direito Constitucional",
        "nivel": "Doutorado",
        "area": "Humanas",
        "assuntos": ["constitucionalismo", "direitos fundamentais", "jurisdição constitucional", "teoria do estado"],
        "duracao_meses": 48,
        "horario": "Vespertino",
        "modalidade": "Presencial",
        "preco_mensal": 0.00,
        "instituicao": "USP",
        "cidade": "São Paulo",
        "nota_mec": 7,
        "descricao": "Doutorado em Direito com biblioteca jurídica referência na América Latina."
    },
    {
        "id": 27,
        "nome": "Doutorado em Engenharia de Materiais",
        "nivel": "Doutorado",
        "area": "Engenharia",
        "assuntos": ["nanotecnologia", "materiais compósitos", "metalurgia", "cerâmicas avançadas"],
        "duracao_meses": 48,
        "horario": "Integral",
        "modalidade": "Presencial",
        "preco_mensal": 0.00,
        "instituicao": "UFSCar",
        "cidade": "São Carlos",
        "nota_mec": 7,
        "descricao": "Doutorado com laboratórios de caracterização de materiais e parcerias com indústria."
    },

    # ============ PÓS-DOUTORADO ============
    {
        "id": 28,
        "nome": "Pós-doutorado em Computação Quântica",
        "nivel": "Pós-doutorado",
        "area": "Tecnologia",
        "assuntos": ["algoritmos quânticos", "criptografia quântica", "hardware quântico", "simulação quântica"],
        "duracao_meses": 24,
        "horario": "Integral",
        "modalidade": "Presencial",
        "preco_mensal": 0.00,
        "instituicao": "USP/IFUSP",
        "cidade": "São Paulo",
        "nota_mec": 7,
        "descricao": "Pós-doc em computação quântica com acesso a computadores quânticos IBM e bolsa FAPESP."
    },
    {
        "id": 29,
        "nome": "Pós-doutorado em Neurociência Computacional",
        "nivel": "Pós-doutorado",
        "area": "Saúde",
        "assuntos": ["modelagem neural", "brain-computer interface", "neuroimagem avançada", "IA aplicada ao cérebro"],
        "duracao_meses": 24,
        "horario": "Integral",
        "modalidade": "Presencial",
        "preco_mensal": 0.00,
        "instituicao": "IDOR",
        "cidade": "Rio de Janeiro",
        "nota_mec": 7,
        "descricao": "Pós-doc interdisciplinar entre neurociência e IA com colaboração internacional."
    },
    {
        "id": 30,
        "nome": "Pós-doutorado em Energia Renovável",
        "nivel": "Pós-doutorado",
        "area": "Engenharia",
        "assuntos": ["energia solar", "eólica", "hidrogênio verde", "armazenamento de energia"],
        "duracao_meses": 24,
        "horario": "Integral",
        "modalidade": "Presencial",
        "preco_mensal": 0.00,
        "instituicao": "INPE",
        "cidade": "São José dos Campos",
        "nota_mec": 7,
        "descricao": "Pesquisa avançada em fontes de energia limpa com financiamento de agências internacionais."
    },
    {
        "id": 31,
        "nome": "Pós-doutorado em Biotecnologia",
        "nivel": "Pós-doutorado",
        "area": "Saúde",
        "assuntos": ["biologia sintética", "engenharia genética", "bioprocessos", "vacinas"],
        "duracao_meses": 36,
        "horario": "Integral",
        "modalidade": "Presencial",
        "preco_mensal": 0.00,
        "instituicao": "Instituto Butantan",
        "cidade": "São Paulo",
        "nota_mec": 7,
        "descricao": "Pós-doc em biotecnologia com foco em desenvolvimento de vacinas e biofármacos."
    },
    {
        "id": 32,
        "nome": "Pós-doutorado em Economia Digital",
        "nivel": "Pós-doutorado",
        "area": "Negócios",
        "assuntos": ["blockchain", "fintech", "economia de plataformas", "regulação digital"],
        "duracao_meses": 18,
        "horario": "Integral",
        "modalidade": "Híbrido",
        "preco_mensal": 0.00,
        "instituicao": "Insper",
        "cidade": "São Paulo",
        "nota_mec": 6,
        "descricao": "Pós-doc em economia digital com foco em criptoativos e regulação de fintechs."
    },
]

# Listas de opções para os filtros
NIVEIS = ["Técnico", "Graduação", "Pós-graduação", "Mestrado", "Doutorado", "Pós-doutorado"]

AREAS = ["Tecnologia", "Saúde", "Engenharia", "Negócios", "Humanas", "Artes e Design"]

HORARIOS = ["Matutino", "Vespertino", "Noturno", "Integral", "Sábados"]

MODALIDADES = ["Presencial", "EAD", "Híbrido"]

CIDADES = list(set(course["cidade"] for course in COURSES))
CIDADES.sort()

INSTITUICOES = list(set(course["instituicao"] for course in COURSES))
INSTITUICOES.sort()
